
language: node_js

node_js:
  - "12"

script:
  - npm run lint
  - ./build/process-template.sh remote-resources/configmap02-rr.yaml > /tmp/configmap02-rr.yaml
  - ./build/process-template.sh remote-resources/configmap02.yaml > /tmp/configmap02.yaml

deploy:
  # Deploy remote-resource builds
  - provider: releases
    file:
      - /tmp/configmap02-rr.yaml
    skip_cleanup: true
    draft: true
    api_key:
      secure: "${GITHUB_TOKEN}"
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+_[0-9]{3}$
